# Generated by Django 5.1 on 2024-09-03 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                ("special_id", models.AutoField(primary_key=True, serialize=False)),
                ("special_name", models.CharField(max_length=50)),
                ("area_name", models.CharField(default="none", max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("doctor_id", models.AutoField(primary_key=True, serialize=False)),
                ("doctor_name", models.CharField(max_length=50)),
                ("doctor_phone", models.CharField(max_length=50)),
                ("doctor_address", models.CharField(max_length=50)),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Doctors.specialization",
                    ),
                ),
            ],
        ),
    ]
