# Generated by Django 5.1 on 2024-09-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("userId", models.AutoField(primary_key=True, serialize=False)),
                ("userName", models.CharField(max_length=50)),
                ("userEmail", models.CharField(max_length=50)),
                ("userPassword", models.CharField(max_length=50)),
                ("isActive", models.BooleanField(default=True)),
            ],
        ),
    ]
